language: node_js
node_js: 10
cache: npm
install:
  - npm i
branches:
  only:
  - dev
deploy:
  api_key:
    secure: WqWZcKVtaeSHW9WRe4ozuxiW91rytdU8e6lFF6w4Nxk+U0dI6zfl+rUgk84l5eV8UNvA9cZcFvskFIL7bQdurrg4O2z4igzMCmoZcEvBL2rwM1WVnrX8b0wV/Z8mDqjM+2B3IM7yxfZRMuHsn3Z3R+Dn9EHCIEavDzex3Cr1uqRSMbCx48tTAqNdb+SfErb/SGt19RTjDBAWFWEIwqcjEpEStbGTBqNJrzTn5e/YlsFISsEPHzjmKqebpDdCilKPOtW4eHifUg8IXAz+fOJeyNksAlkEbFB1/cTH5RGJ+irCbcpkMJlLwR/Eqje3JZnBHwWGLnZlBjkpWP+9rZK9RpTEfIpij8HlbXrOCDOQ74UruY3tEgYAwzhPt3omTlRNE52islqEqsBihAvGCY/jffEKX3cq27lK5Dmcs08rfREXL86LkTuko5T9ZmLnzTpNZQmGM+D/CX5zDuKWbk30YSZgXXYN27vsJjATrZ0uj08ftMa4+WFkuCDz6tglLkJ1nRGnJs7nYpznVyGdN7Y17y/SJu8mOWlDVxk7GMeLXINbTfXmxupFr1e95ABN0qBqIYShlZppMOG3CMgdSei7Ob/iEf3+EpNMakTSMI5Mii54B1Vwv/O2D4tOfl4pMOPr5KF2TxFj2p4bdiazEQPmCW0G+/0A/rBNVUQ5KYu/VuA=
    dev: iwnodeapp